[package]
name = "web_scraper_hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
anyhow = { version = "1.0"} 
log = "0.4.21"
env_logger = "0.11.3"
reqwest = { version = "0.12", features = ["json"] }
openssl = "0.10.64"
